name: Go

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  FORCE_COLOR: "1"  # Needed to run tests

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build for Linux
      run: go build -o pipecolor ./...

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o pipecolor.exe ./...

    - name: Test
      run: go test -v ./...

    - name: Create artifacts
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir -p artifacts/linux
        mv pipecolor artifacts/linux/
        mkdir -p artifacts/windows
        mv pipecolor.exe artifacts/windows/

    - name: Upload artifact
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v2
      with:
        name: pipecolor
        path: artifacts/

    - name: Release with Notes
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/linux/pipecolor
          artifacts/windows/pipecolor.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
